### PR TITLE
Minor (Updated editor docs hyperlinks to public repo)

### PR DESCRIPTION
**Pull request by Myrkie**
Updated all docs hyperlinks to use the public MarrowSDK repo wiki pages.

### CODE REVIEW

**Comment by CuteWaterbeary** [comment]
This will be fixed in the next official MarrowSDK update

_Originally posted by @Greased-Scotsman in https://github.com/StressLevelZero/MarrowSDK/issues/37#issuecomment-1264533709_
      

The next official MarrowSDK update came out and this was still not fixed: https://github.com/StressLevelZero/MarrowSDK/tree/b8cfc6f061ad3bcafe5583664bca4acb327cd923

Why are you guys closing pull requests and issues prematurely? 

#37
#25 
#1

**Comment by valentinegb** [comment]
@CuteWaterbeary I closed my own issue. As far as I can tell from using the SDK, this issue has been resolved.

**Comment by Myrkie** [comment]
seems a big like they are managing bug reports in an internal bug tracker and closing based on commits, that saying this pull request was never merged they fixed it themselves through another commit so the discussing for that shouldn't be done here. https://github.com/StressLevelZero/MarrowSDK/commit/bc50d82a1176d964d8f1f65e976e9fd2ef5841c1

**Comment by yewnyx** [comment]
@CuteWaterbeary Apologies if it isn't clear, but the code in this repository is machine-generated from a subset of our internal repositories, via our CI. We don't currently have any plans to accept pull requests at this time, and any such workflow would most likely require a significant amount of rework to accommodate.

**Comment by Myrkie** [comment]
> @CuteWaterbeary Apologies if it isn't clear, but the code in this repository is machine-generated from a subset of our internal repositories, via our CI. We don't currently have any plans to accept pull requests at this time, and any such workflow would most likely require a significant amount of rework to accommodate.

use of github copilot?

**Comment by valentinegb** [comment]
> @CuteWaterbeary Apologies if it isn't clear, but the code in this repository is machine-generated from a subset of our internal repositories, via our CI. We don't currently have any plans to accept pull requests at this time, and any such workflow would most likely require a significant amount of rework to accommodate.

I had thought so, considering an internal repository was referenced in the code. It is a bit unfortunate though, I think community pull requests could be beneficial.

**Comment by CuteWaterbeary** [comment]
Thank you for the explanations and for resolving the license issue =)

**Pull request closed without merging**
